2021-01-07 15:22:30,405 main.py[line:53] INFO {'binding status': 1}
2021-01-07 15:22:33,409 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:22:33,409 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:22:43,411 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:22:43,411 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:22:53,411 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:22:53,411 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:23:03,419 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:23:03,421 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:23:13,426 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:23:13,426 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:23:23,428 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:23:23,428 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:23:33,429 main.py[line:95] ERROR restart get_com_data_thread
2021-01-07 15:23:33,429 main.py[line:100] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:25:31,793 main.py[line:53] INFO {'binding status': 1}
2021-01-07 15:25:34,795 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:25:34,795 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:25:44,796 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:25:44,796 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:25:54,797 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:25:54,797 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:06,034 main.py[line:53] INFO {'binding status': 1}
2021-01-07 15:27:09,036 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:09,036 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:19,037 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:19,037 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:29,040 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:29,040 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:39,041 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:39,041 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:49,041 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:49,041 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:27:59,043 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:27:59,043 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:09,046 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:09,046 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:19,048 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:19,048 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:29,049 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:29,049 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:39,051 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:39,051 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:49,054 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:49,054 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:28:59,056 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:28:59,056 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:09,056 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:09,056 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:19,057 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:19,057 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:29,058 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:29,058 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:39,058 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:39,058 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:49,058 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:49,058 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:29:59,061 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:29:59,061 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:09,062 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:09,062 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:19,063 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:19,063 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:29,063 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:29,063 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:39,064 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:39,064 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:49,065 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:49,065 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:30:59,066 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:30:59,066 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:09,067 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:09,067 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:19,068 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:19,068 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:29,069 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:29,069 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:39,069 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:39,069 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:49,070 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:49,070 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:31:59,073 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:31:59,073 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:09,074 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:09,074 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:19,074 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:19,074 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:29,075 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:29,075 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:39,075 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:39,075 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:49,076 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:49,076 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:32:59,078 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:32:59,078 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:09,078 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:09,079 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:19,079 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:19,079 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:29,080 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:29,081 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:39,082 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:39,082 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:49,082 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:49,082 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:33:59,083 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:33:59,083 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:09,084 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:09,084 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:19,084 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:19,084 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:29,085 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:29,085 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:39,086 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:39,086 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:49,087 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:49,087 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:34:59,087 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:34:59,087 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:09,087 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:09,087 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:19,089 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:19,089 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:29,090 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:29,090 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:39,091 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:39,091 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:49,093 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:49,093 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:35:59,094 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:35:59,094 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:09,095 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:09,095 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:19,096 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:19,096 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:29,098 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:29,098 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:39,100 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:39,100 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:49,100 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:49,100 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:36:59,101 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:36:59,101 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:09,101 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:09,101 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:19,101 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:19,101 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:29,102 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:29,102 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:39,103 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:39,103 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:49,104 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:49,104 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:37:59,104 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:37:59,104 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:09,106 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:09,107 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:19,108 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:19,108 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:29,108 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:29,108 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:39,109 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:39,110 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:49,111 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:49,111 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:38:59,112 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:38:59,112 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:09,113 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:09,113 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:19,113 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:19,113 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:29,115 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:29,115 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:39,116 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:39,116 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:49,118 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:49,118 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:39:59,120 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:39:59,120 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:09,122 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:09,122 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:19,122 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:19,122 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:29,122 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:29,122 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:39,123 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:39,123 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:49,123 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:49,123 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:40:59,124 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:40:59,124 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:09,126 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:09,126 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:19,129 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:19,129 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:29,131 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:29,131 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:39,132 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:39,132 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:49,132 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:49,132 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:41:59,133 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:41:59,133 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:09,133 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:09,133 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:19,134 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:19,134 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:29,135 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:29,135 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:39,136 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:39,136 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:49,136 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:49,137 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:42:59,139 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:42:59,139 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:09,140 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:09,140 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:19,142 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:19,142 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:29,143 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:29,143 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:39,146 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:39,146 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:49,146 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:49,146 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:43:59,147 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:43:59,148 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:09,148 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:09,148 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:19,149 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:19,149 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:29,149 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:29,149 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:39,152 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:39,152 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:49,153 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:49,153 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:44:59,153 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:44:59,153 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:09,154 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:09,154 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:19,155 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:19,155 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:29,156 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:29,156 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:39,156 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:39,156 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:49,157 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:49,157 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:45:59,158 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:45:59,158 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:46:09,159 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:46:09,159 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:46:19,160 main.py[line:96] ERROR restart get_com_data_thread
2021-01-07 15:46:19,160 main.py[line:101] ERROR {'´®¿Ú¹Ø±ÕÊ§°Ü': 111, 'error': AttributeError("'SerialData' object has no attribute 'uart'")}
2021-01-07 15:46:26,159 main.py[line:53] INFO {'binding status': 1}
2021-01-07 15:51:33,339 main.py[line:53] INFO {'binding status': 1}
2021-01-07 15:56:14,998 main.py[line:53] INFO {'binding status': 1}
2021-01-07 16:06:03,371 main.py[line:53] INFO {'binding status': 1}
2021-01-07 16:27:02,959 main.py[line:53] INFO {'binding status': 1}
2021-01-07 16:29:02,063 main.py[line:53] INFO {'binding status': 1}
2021-01-07 16:30:51,220 main.py[line:53] INFO {'binding status': 1}
2021-01-07 16:43:21,100 main.py[line:53] INFO {'binding status': 1}
2021-01-07 17:09:27,878 main.py[line:53] INFO {'binding status': 1}
2021-01-07 17:09:37,884 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:09:47,884 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:09:57,885 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:07,885 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:17,885 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:27,885 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:37,886 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:47,887 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:10:57,887 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:11:07,888 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:11:17,890 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:11:31,715 main.py[line:53] INFO {'binding status': 1}
2021-01-07 17:11:46,724 main.py[line:133] ERROR restart check_status_thread
2021-01-07 17:17:19,212 main.py[line:53] INFO {'binding status': 1}
2021-01-07 17:26:34,100 main.py[line:53] INFO {'binding status': 1}
2021-01-08 09:28:12,979 main.py[line:52] INFO {'binding status': 1}
2021-01-08 09:32:19,597 main.py[line:52] INFO {'binding status': 1}
2021-01-08 09:32:50,893 main.py[line:52] INFO {'binding status': 1}
2021-01-08 09:46:35,198 main.py[line:52] INFO {'binding status': 1}
2021-01-08 09:53:22,131 main.py[line:52] INFO {'binding status': 1}
2021-01-08 10:13:03,085 main.py[line:52] INFO {'binding status': 1}
2021-01-08 10:44:10,739 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 10:44:32,744 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 10:44:54,749 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 10:45:16,753 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 10:45:39,757 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 10:45:49,760 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 11:02:03,837 main.py[line:124] ERROR restart send_mqtt_data_thread
2021-01-08 11:07:09,291 main.py[line:52] INFO {'binding status': 1}
2021-01-08 11:10:59,477 main.py[line:52] INFO {'binding status': 1}
2021-01-08 14:22:32,333 main.py[line:52] INFO {'binding status': 1}
